# Use an official Node.js runtime as a parent image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json (if available)
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Bundle the source code inside the Docker container
COPY . .

# Make port 3030 available to the world outside this container
EXPOSE 3030

# Command to run the app
CMD ["npm", "start"]
